name: My App CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: linux
    java-version: 21
    steps:
      - name: Checkout
        uses: git-checkout
      - name: Build
        run: mvn clean package -DskipTests
      - name: Test
        run: mvn test